version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: gaole/deeplearning-container:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
    volumes:
      - /Users:/Users
      - /etc/config.txt:/config.txt
networks:
  webnet:
